[build]
  publish = "client/dist"
  command = "cd client && npm i && npm run build"

[functions]
  directory = "client/functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200