[build]
  base    = "client"
  publish = "dist"
  command = "npm run build"
  external_node_modules = ["utils, server/models"]

[functions]
  directory = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"
