[build]
  base    = "client"
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[headers]]
  # For your functions endpoints
  for = "/.netlify/functions/*"

    [headers.Access-Control-Allow-Origin]
      origin = "*"

    [headers.Access-Control-Allow-Headers]
      headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

    [headers.Access-Control-Allow-Methods]
      methods = "GET, POST, PUT, DELETE, OPTIONS"

